=head1 NAME

Mono::ID - Mono ID convertions

=head1 DESCRIPTION

TBD.

=head1 AUTHOR

Wakaba <wakabatan@hatena.ne.jp>.

=head1 ACKNOWLEDGEMENTS

Many of functions in this module was originally written by cho45 for
Hatena Monolith and then moved into a standalone module by Wakaba for
Hatena Haiku 2010 project.

=head1 LICENSE

Copyright 2010-2012 Hatena <http://www.hatena.com/>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
